import { MatchLineupData } from './types';



export const matchLineupData: MatchLineupData = {
  event_id: 'MATCH2025-05-07',
  lineup: {
    home: {
      team_id: 'nagoya_grampus',
      team_name: '名古屋八鲸',
      team_logo: 'https://img0.aiscore.com/football/team/f01ecc34c5814c9b486657bc3143b3b0.png!w60',
      formation: '3-4-1-2',
      coach: {
        name: '长谷川健太',
      },
      starting_lineups: [
        {
          player_id: 'H1',
          photo: 'https://img0.aiscore.com/football/player/8984d1bcee77a96c84c903bf4ce1fede.jpg!w100',
          name: '兰基戴尔',
          shirt_number: 35,
          position: 'GK',
          is_captain: false,
          rating: 6.8,
        },
      
        {
          player_id: 'H2',
          photo: 'https://img0.aiscore.com/football/player/8984d1bcee77a96c84c903bf4ce1fede.jpg!w100',
          name: '奥藤诚',
          shirt_number: 70,
          position: 'DF',
          is_captain: false,
          rating: 6.6,
          events: [{ type: 'own_goal', minute: 26 }],
        },
        {
          player_id: 'H3',
          photo: 'https://img0.aiscore.com/football/player/438b0c913b82aa237ab68bb1daf4520d.png!w100',
          name: '蓝尼治',
          shirt_number: 20,
          position: 'DF',
          is_captain: false,
          rating: 6.9,
          events: [{ type: 'yellow_card', minute: 5 },{ type: 'goal', minute: 16 },{ type: 'penalty_goal', minute: 46 }],
        },
       
        {
          player_id: 'H4',
          photo: 'https://img0.aiscore.com/football/player/438b0c913b82aa237ab68bb1daf4520d.png!w100',
          name: '若原悠大',
          shirt_number: 3,
          position: 'DF',
          is_captain: false,
          rating: 7.1,
          events: [{ type: 'goal', minute: 6 },{ type: 'own_goal', minute: 12 },{ type: 'penalty_goal', minute: 46 },{ type: 'missed_penalty', minute: 46 }],
        },
        {
          player_id: 'H5',
          photo: 'https://img0.aiscore.com/football/player/438b0c913b82aa237ab68bb1daf4520d.png!w100',
          name: '内田宅哉',
          shirt_number: 17,
          position: 'DF',
          is_captain: false,
          rating: 6.3,
          events: [{ type: 'second_yellow', minute: 10 },{ type: 'second_yellow', minute: 10 }],
        },
        {
          player_id: 'H6',
          photo: 'https://img0.aiscore.com/football/player/438b0c913b82aa237ab68bb1daf4520d.png!w100',
          name: '稻垣祥',
          shirt_number: 15,
          position: 'MF',
          is_captain: false,
          rating: 6.4,
        },
        {
          player_id: 'H7',
          photo: 'https://img0.aiscore.com/football/player/438b0c913b82aa237ab68bb1daf4520d.png!w100',
          name: '椎桥慧也',
          shirt_number: 8,
          position: 'MF',
          is_captain: false,
          rating: 6.3,
          events: [{ type: 'yellow_card', minute: 10 },{ type: 'second_yellow', minute: 15 },{ type: 'sub_out', minute: 85 }],
        },
        {
          player_id: 'H8',
          photo: 'https://img0.aiscore.com/football/player/438b0c913b82aa237ab68bb1daf4520d.png!w100',
          name: '德元亮平',
          shirt_number: 55,
          position: 'MF',
          is_captain: false,
          rating: 6.3,
          events: [{ type: 'sub_out', minute: 46 }],
        },
        {
          player_id: 'H9',
          photo: 'https://img0.aiscore.com/football/player/8984d1bcee77a96c84c903bf4ce1fede.jpg!w100',
          name: '和泉竜司',
          shirt_number: 7,
          position: 'FW',
          role: 'CAM', // 可选字段，细化位置
          is_captain: false,
          rating: 6.0,
          events: [{ type: 'sub_out', minute: 66 }],
        },
        {
          player_id: 'H10',
          photo: 'https://img0.aiscore.com/football/player/438b0c913b82aa237ab68bb1daf4520d.png!w100',
          name: '永井谦佑',
          shirt_number: 18,
          position: 'FW',
          is_captain: false,
          rating: 7.0,
          events: [{ type: 'sub_out', minute: 46 }],
        },
        {
          player_id: 'H11',
          photo: 'https://img0.aiscore.com/football/player/438b0c913b82aa237ab68bb1daf4520d.png!w100',
          name: '马修斯',
          shirt_number: 10,
          position: 'FW',
          is_captain: false,
          rating: 6.1,
          events: [{ type: 'sub_out', minute: 66 }],
        },
      ],
      substitutes: [
        {
          player_id: 'H12',
          photo: 'https://img0.aiscore.com/football/player/438b0c913b82aa237ab68bb1daf4520d.png!w100',
          name: '虎考',
          shirt_number: 99,
          position: 'FW',
          is_captain: false,
          rating: 6.0,
          events: [{ type: 'sub_in', minute: 72 }],
        },
      ],
      missing_players: [],
    },

    away: {
      team_id: 'okayama',
      team_name: '冈山绿雉',
      team_logo: 'https://img0.aiscore.com/football/team/fb5c6121bf5b351f60ebf8ffd5b9d887.png!w100',
      formation: '3-4-2-1',
      coach: {
        name: '木山隆之',
      },
      starting_lineups: [
        {
          player_id: 'A1',
          photo: 'https://img0.aiscore.com/football/player/438b0c913b82aa237ab68bb1daf4520d.png!w100',
          name: '保坂匠',
          shirt_number: 49,
          position: 'GK',
          is_captain: false,
          rating: 6.6,
        },
        {
          player_id: 'A2',
          photo: 'https://img0.aiscore.com/football/player/438b0c913b82aa237ab68bb1daf4520d.png!w100',
          name: '工藤孝大',
          shirt_number: 15,
          position: 'DF',
          is_captain: false,
          rating: 6.1,
        },
        {
          player_id: 'A3',
          photo: 'https://img0.aiscore.com/football/player/438b0c913b82aa237ab68bb1daf4520d.png!w100',
          name: '立田悠悟',
          shirt_number: 2,
          position: 'DF',
          is_captain: false,
          rating: 6.8,
        },
        {
          player_id: 'A4',
          photo: 'https://img0.aiscore.com/football/player/438b0c913b82aa237ab68bb1daf4520d.png!w100',
          name: '阿部海大',
          shirt_number: 4,
          position: 'DF',
          is_captain: false,
          rating: 6.3,
        },
        {
          player_id: 'A5',
          photo: 'https://img0.aiscore.com/football/player/438b0c913b82aa237ab68bb1daf4520d.png!w100',
          name: '加藤健人',
          shirt_number: 50,
          position: 'DF',
          is_captain: false,
          rating: 5.9,
          events: [{ type: 'yellow_card', minute: 83 }],
        },
        {
          player_id: 'A6',
          photo: 'https://img0.aiscore.com/football/player/438b0c913b82aa237ab68bb1daf4520d.png!w100',
          name: '田部井涼',
          shirt_number: 14,
          position: 'MF',
          is_captain: false,
          rating: 6.3,
          events: [{ type: 'sub_out', minute: 61 }],
        },
        {
          player_id: 'A7',
          photo: 'https://img0.aiscore.com/football/player/438b0c913b82aa237ab68bb1daf4520d.png!w100',
          name: '藤田息吹',
          shirt_number: 24,
          position: 'MF',
          is_captain: false,
          rating: 6.4,
        },
        {
          player_id: 'A8',
          photo: 'https://img0.aiscore.com/football/player/438b0c913b82aa237ab68bb1daf4520d.png!w100',
          name: '柴本苍太',
          shirt_number: 28,
          position: 'MF',
          is_captain: false,
          rating: 6.4,
        },
        {
          player_id: 'A9',
          photo: 'https://img0.aiscore.com/football/player/438b0c913b82aa237ab68bb1daf4520d.png!w100',
          name: '岩渊弘人',
          shirt_number: 19,
          position: 'MF',
          role: 'CAM', // 可选字段，细化位置
          is_captain: false,
          rating: 6.5,
          events: [
            { type: 'sub_out', minute: 46 },
            { type: 'yellow_card', minute: 20 },
          ],
        },
        {
          player_id: 'A10',
          photo: 'https://img0.aiscore.com/football/player/438b0c913b82aa237ab68bb1daf4520d.png!w100',
          name: '江坂任',
          shirt_number: 8,
          position: 'FW',
          role: 'CAM', // 可选字段，细化位置
          is_captain: false,
          rating: 5.9,
          events: [{ type: 'sub_out', minute: 72 }],
        },
        {
          player_id: 'A11',
          photo: 'https://img0.aiscore.com/football/player/438b0c913b82aa237ab68bb1daf4520d.png!w100',
          name: '虚考',
          shirt_number: 93,
          position: 'FW',
          is_captain: false,
          rating: 6.0,
        },
      ],
      substitutes: [],
      missing_players: [
        {
            player_id: "A15",
            name: "佐藤健太",
            shirt_number: 31,
            position: "DF",
            is_captain: false,
            photo: "https://img.aiscore.com/player/xxx3.png",
            status: 'missing',
            unavailable_reason:'injured'
          },
          {
            player_id: "A16",
            name: "田岛诚",
            shirt_number: 18,
            position: "MF",
            is_captain: false,
            photo: "https://img.aiscore.com/player/xxx4.png",
            status: 'missing',
            unavailable_reason:'suspended'
          }
      ],
    },
  },
};
