// src/router/routes.tsx
import React, { lazy } from 'react';
import { createBrowserRouter, HashRouter, Navigate, RouterProvider } from 'react-router-dom';
import routesJonFile from './routes.json';
import { IFRouterConfig } from './interface';
import AuthGuard from './authGuard'; // 导入 AuthGuard 组件
import { RouterPathUtil } from './routerPathUtil';
import { lazyRouteMap } from './autoGeneratedLazyMap'; 
const LazyComponentComp = (comp: string): React.LazyExoticComponent<React.ComponentType<any>> => {
  const loader = lazyRouteMap[comp];
  return lazy(() =>
    loader().catch((err): { default: React.ComponentType<any> } => {
      console.error('LazyComponentComp 懒加载失败:', err);
      return {
        default: () => <div>页面加载失败</div>,
      };
    })
  );
};

const generateReactRouterRoutes = (config: IFRouterConfig[]) => {
  return config.map((route) => {
    const { component, path, children, author = false, index,customPath,fullPath,name,  ...rest } = route;
    const LazyComponent = component  ? LazyComponentComp(component): null;
    const element = LazyComponent ? (
      <AuthGuard author={author}>
        <LazyComponent />
      </AuthGuard>
    ) : undefined;

    const reactRouterRoute: any = {
      ...(index ? { index: true } : { path: customPath || path }),
      element,
      ...rest,
    };
    if (children?.length && !index) {
      reactRouterRoute.children = generateReactRouterRoutes(children);
    }

    return reactRouterRoute;
  });
};
/**
 * 这种事不使用index的情况，<Layout/>组件去指定具体跳转路径
 */
/**
 * 
  const updatedRoutesConfig = [
    {
      path: '/',
      element:<Layout/>,
      children:[
        ...routesJonFile
      ]
    },
    {
      path: '*',
      element: <Navigate to="/" replace />,
    },
  ];
 */
/**
 * 这种是使用index的情况，根据routerConfig.ts中指定index为默认路由的结构
 */
const updatedRoutesIndexConfig = [
  {
    path: '/',
    children:[
      {
        index: true,
        element: <Navigate to={RouterPathUtil.HOME} replace />
      },
      ...routesJonFile
    ]
  },
  {
    path: '*',
    element: <Navigate to="/" replace />,
  },
];

const routes =generateReactRouterRoutes(updatedRoutesIndexConfig as IFRouterConfig[])
console.log('last routes--',routes)
 const resRoutes=createBrowserRouter(routes);

const AppRouter = () => {
   return <RouterProvider router={resRoutes}   />
};

export default AppRouter;