export enum RouterPathUtil {
  MAIN = '/main',
  MAIN_AMERICALBALL = '/main/americalBall',
  MAIN_BADMINTON = '/main/badminton',
  MAIN_BASEBALL = '/main/baseball',
  MAIN_BASKETBALL = '/main/basketball',
  MAIN_CRICKET = '/main/cricket',
  MAIN_ESPORTS = '/main/esports',
  MAIN_FAVORITE = '/main/favorite',
  MAIN_FOOTBALL = '/main/football',
  MAIN_HANDBALL = '/main/handball',
  MAIN_ICEHOCKEY = '/main/iceHockey',
  MAIN_MENU = '/main/menu',
  MAIN_SERCH = '/main/serch',
  MAIN_SNOOKER = '/main/snooker',
  MAIN_TABLETENNIS = '/main/tableTennis',
  MAIN_TENNIS = '/main/tennis',
  MAIN_VOLLEYBALL = '/main/volleyball',
  MAIN_WATERPOLO = '/main/waterpolo',
  MATCHDETAILS = '/matchDetails',
}
