export enum RouterPathUtil {
  HOME = '/home',
  HOME_AMERICALBALL = '/home/americalBall',
  HOME_BADMINTON = '/home/badminton',
  HOME_BASEBALL = '/home/baseball',
  HOME_BASKETBALL = '/home/basketball',
  HOME_CRICKET = '/home/cricket',
  HOME_ESPORTS = '/home/esports',
  HOME_FAVORITE = '/home/favorite',
  HOME_FOOTBALL = '/home/football',
  HOME_HANDBALL = '/home/handball',
  HOME_ICEHOCKEY = '/home/iceHockey',
  HOME_MENU = '/home/menu',
  HOME_SERCH = '/home/serch',
  HOME_SNOOKER = '/home/snooker',
  HOME_TABLETENNIS = '/home/tableTennis',
  HOME_TENNIS = '/home/tennis',
  HOME_VOLLEYBALL = '/home/volleyball',
  HOME_WATERPOLO = '/home/waterpolo',
  MATCHDETAILS = '/matchDetails',
}
