export enum RouterPathUtil {
  ACCOUNT = '/account',
  ACCOUNT_LOGIN = '/account/login',
  ACCOUNT_REGIST = '/account/regist',
  HOME = '/home',
  HOME_AMERICALBALL = '/home/americalBall',
  HOME_BADMINTON = '/home/badminton',
  HOME_BASEBALL = '/home/baseball',
  HOME_BASKETBALL = '/home/basketball',
  HOME_CRICKET = '/home/cricket',
  HOME_ESPORTS = '/home/esports',
  HOME_FAVORITE = '/home/favorite',
  HOME_FOOTBALL = '/home/football',
  HOME_HANDBALL = '/home/handball',
  HOME_ICEHOCKEY = '/home/iceHockey',
  HOME_SNOOKER = '/home/snooker',
  HOME_TABLETENNIS = '/home/tableTennis',
  HOME_TENNIS = '/home/tennis',
  HOME_VOLLEYBALL = '/home/volleyball',
  HOME_WATERPOLO = '/home/waterpolo',
  MATCHDETAILS = '/matchDetails',
  TEAMDETAILS = '/teamDetails',
  TEAMDETAILS_BASKETBALL = '/teamDetails/basketball',
  TEAMDETAILS_FOOTBALL = '/teamDetails/football',
}
