/*
 * @Author: Mark
 * @Date: 2025-06-08 16:59:55
 * @LastEditTime: 2025-06-08 16:59:56
 * @LastEditors: MarkMark
 * @Description: 佛祖保佑无bug
 * @FilePath: /hb_aiScore/scripts/generate-LazyMap.ts
 */
// scripts/generateLazyMap.js
const fs = require("fs");
const path = require("path");

// 读取 routes.json
const routes = require(path.resolve(__dirname, "../src/router/routes.json"));
const targetPath = path.resolve(
  __dirname,
  "../src/router/autoGeneratedLazyMap.ts"
);

const componentSet = new Set();

function extractComponentPaths(routes) {
  routes.forEach((route) => {
    if (route.component) {
      componentSet.add(route.component);
    }
    if (Array.isArray(route.children)) {
      extractComponentPaths(route.children);
    }
  });
}

// 提取所有 component 字段
extractComponentPaths(routes);

// 构建懒加载映射内容
const importLines = Array.from(componentSet).map(
  (comp) => `  '${comp}': () => import('@/views/${comp}.tsx')`
);

const output = `// ⚠️ 此文件由 generate-LazyMap.js 自动生成，请勿手动修改
import type { ComponentType } from 'react';
export const lazyRouteMap: Record<string, () => Promise<{ default: ComponentType<any> }>> = {
${importLines.join(",\n")}
};
`;

fs.writeFileSync(targetPath, output, "utf8");
console.log(
  `✅ 懒加载映射 lazyRouteMap.ts 已生成，共 ${componentSet.size} 个组件。`
);
